### ISSUE TITLE
Unable to open some external sites

### ISSUE THREAD

**Issue by AHarouni** [trungleduc/jupyter_app_launcher#21]
Thanks for building this, very useful 

I managed to get this to work and open some external sites.
however some other sites refuse the connection with error as 
`github.com refused connection` 

chrome debug tools show error 
```
Refused to frame 'https://github.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

to reproduce try 
```
- catalog: GitHub
  title: test
  description: github
  source: https://github.com
  type: url
```
FYI I launch my jupyter lab without tokens on http connection if that makes any difference

**Comment by trungleduc** [comment]
It's the security policy of Github and is not related to the extension.
