### ISSUE TITLE
Feature request: open Notebook without making a copy

### ISSUE THREAD

**Issue by AHarouni** [trungleduc/jupyter_app_launcher#23]
I managed to use the open existing notebook using `type : notebook` it creates a new notebook for me and I can run it.
However, since it creates a copy of the notebook all the links and images are broken as my notebook is in another sub folder. I could have fixed with the `cmd` option to launch from a certain subfolder. unfortunately it is disabled

I guess the ask can be simpler if we can just add links/shortcuts to open existing notebooks from subfolders instead of copying then launching.

**Comment by trungleduc** [comment]
Thanks for your feedback, can you close the issues which are resolved?

**Comment by trungleduc** [comment]
Due to the limit of the Jupyter server, opening a notebook located outside of the root path of the server is not allowed.
