### ISSUE TITLE
Run bash script with launcher entry

### ISSUE THREAD

**Issue by TidbitSoftware** [trungleduc/jupyter_app_launcher#25]
Is there a known way to use your extension to run a bash script with a launcher entry?

**Comment by trungleduc** [comment]
Hi, it's not possible out of the box. You can create a simple python server using `http.server` that runs your bash script and servers the output of the script. Then you can use the [`local-server`](https://jupyter-app-launcher.readthedocs.io/en/latest/usage.html#start-a-local-process-and-open-the-predefined-url) launcher to run your bash script and get the result in `JupyterLab`
