### ISSUE TITLE
Jupyter Server 2.5 dependency error 

### ISSUE THREAD

**Issue by luanabeckerdaluz** [trungleduc/jupyter_app_launcher#30]
When I upgraded the jupyter-server version to 2.5.0, I got a dependency error indicating: 
"jupyter-app-launcher 0.1.6 requires jupyter-server<2,>=1.6, but you have jupyter-server 2.5".

If I try to downgrade jupyter-server version, I got an error on jupyter-server-terminals package that indicated that I need Jupyter Server 2.0+.

I did some tests using the jupyter-app-launcher packages in version 0.1.6 with the jupyter-server 2.5.0 package and it worked, so I think it is just a matter of updating dependencies.

Thanks for your consideration!

**Comment by trungleduc** [comment]
Thanks for your feedback, I'm waiting for JupyterLab 4 (which will be released in 1-2 weeks) before doing the update.

**Comment by dhirschfeld** [comment]
> *package jupyter_app_launcher-0.1.6-pyhd8ed1ab_0 requires jupyter_server >=1.6,<2, but none of the providers can be installed*

This looks like a very useful extension but unfortunately I'm also running into this issue. Commenting here so I can track any progress...

**Comment by trungleduc** [comment]
Hi all, `jupyter_app_launcher` depends on `jupyter-server-proxy` which still depends on `jupyterlab` 3, so I need to wait for this package before upgrading `jupyter_app_launcher`

**Comment by trungleduc** [comment]
PR opened on `jupyter-server-proxy` https://github.com/jupyterhub/jupyter-server-proxy/pull/419
