### ISSUE TITLE
Specify icon for `catalog` group?

### ISSUE THREAD

**Issue by JamesSample** [trungleduc/jupyter_app_launcher#31]
Is there any way to specify the icon for a `catalog` group, in addition to the icons for individual apps?

At present, it seems the catalog row is automatically assigned the same icon as the first app, but it would be great to be able to create a `catalog` for my organisation (either with no icon, or with my organisation's logo) and then add apps to that `catalog` where each app has its own icon. Is this possible?

Thanks for the useful extension!

**Comment by trungleduc** [comment]
Hi, In JupyterLab the catalog icon is not configurable, so changing the current behavior is impossible.
