### ISSUE TITLE
Jupyter Hub implementation

### ISSUE THREAD

**Issue by LuisSoares** [trungleduc/jupyter_app_launcher#32]
Great extension! 
I tried to use it in jupyterhub and it does work very well, but only with the user that has sudo permissions (running the the littlest jupyter hub on ubuntu 18). While the options appear in the launcher of all users, only URLs can be opened, the notebook button is unable to create a notebook (unless is in the user with sudo privileges for which it works flawlessly). Is there any call that requires additional privileges?

**Comment by trungleduc** [comment]
Hi, for the case of the notebook launcher, the extension will read the content of the notebook and then send it to the frontend to create the notebook file https://github.com/trungleduc/jupyter_app_launcher/blob/fc23909eb26ff05bb0369b436755d01f7ddc8101/jupyter_app_launcher/utils.py#L28-L36. 

Maybe normal users do not have the right to read your notebook file.

**Comment by LuisSoares** [comment]
I think it was an issue with the path I was using, changing it to the full path fixed it! Thanks for the prompt reply!
