### ISSUE TITLE
Multiple configuration files

### ISSUE THREAD

**Issue by dokempf** [trungleduc/jupyter_app_launcher#36]
Thanks for this extension! I have written a Python package which ships with an entrypoint to install the jupyter_app_launcher config into the respective Jupyter data directories. For conda-forge packaging, this will happen already during package build, so that installing my conda package will directly show me the icons in the launcher. I really like this approach for my use case, but I have one problem with it: If for some reason, some other package would do the exact same trick, one would overwrite the other's config.

A solution to this would be to not fix the name of the configuration file to `config.yml`, but only fix its location to `PREFIX/jupyter_app_launcher`. The code discovering the config file would then need to glob the path for potential configuration files and use all of them. What do you think?

**Comment by trungleduc** [comment]
Thanks for your suggestion, indeed this a great idea!. I will implement it in the next version, which is blocked by https://github.com/jupyterhub/jupyter-server-proxy/pull/419

**Comment by trungleduc** [comment]
0.2.0 is released with this feature
