### ISSUE TITLE
Add an option to url type to open the remote URL in a new web page

### ISSUE THREAD

**Issue by imcovangent** [trungleduc/jupyter_app_launcher#37]
Closely related to #27 I think it would be great if it is also possible to open remote URLs in a new webpage.

For some webpages it is much nicer to be able to open them in a new tab. Also, some pages are hard to embed in iFrame.

My use case: I want to be able to direct users to tutorial videos on YouTube.

I guess implementing this for the remote URL should be relatively straightforward. If you are open to it, I can make a PR for it.

**Comment by imcovangent** [comment]
Great, see draft PR #38 

Can you have a look at my implementation and let me know if you require anything before the PR can be completed?

If the implementation is agreed, then I will add an example and extend the documentation accordingly.

**Comment by trungleduc** [comment]
Closes as completed
