### ISSUE TITLE
Mismatch between jupyter --path and jupyter_app_launcher's search path 

### ISSUE THREAD

**Issue by Hoseung** [trungleduc/jupyter_app_launcher#39]
Hi, 
Thanks for this great extension! 
I had a minor problem that Jupyter-lab won't find my config.yaml file.
It turned out that the search path your handlers._init_launcher() is different from what I get from `jupyter --path` in the terminal. 
I fixed the problem by simply moving the config file to a new location. 
Just wanted to tell you that the description of ReadMe may not apply to some users. 

`$ jupyter --path` outputs:
config:
    /home/hoseung/miniconda3/envs/myjplab/**etc**/jupyter
    /home/hoseung/.jupyter
    /home/hoseung/.local/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter

The extension's search path:
    /home/hoseung/miniconda3/envs/myjplab/**shared**/jupyter

I think suggestion #36 will probably solve this problem more gracefully.

**Comment by trungleduc** [comment]
Hi, `jupyter_app_launcher` looks at "the data section of the jupyter --path command", and not the `config` section as your comment. #36 will be addressed in the next release.
