### ISSUE TITLE
No support for JupyterLab 4.x.x

### ISSUE THREAD

**Issue by jpweng** [trungleduc/jupyter_app_launcher#42]
The latest version (0.1.7) doesn't support JupyterLab 4.x.x. Installation of both of these versions using `pip` fails.

**Comment by SyrakuShaikh** [comment]
Same here. Any update plan? thanks.

**Comment by trungleduc** [comment]
Yes, the upstream dependencies have been updated recently, I will work on this extension soon.

**Comment by trungleduc** [comment]
0.2.0 is released with jlab4 support
