### ISSUE TITLE
How to use it in Windows

### ISSUE THREAD

**Issue by Orochi-Adde** [trungleduc/jupyter_app_launcher#51]
![image](https://github.com/trungleduc/jupyter_app_launcher/assets/61545076/933ebf5a-24bb-48f1-944e-c570bdb26b3c)
![image](https://github.com/trungleduc/jupyter_app_launcher/assets/61545076/d5da3c94-49c7-4718-861f-c7a39d84413a)

Unable to find the extended configuration path in the window environment

**Comment by Orochi-Adde** [comment]
Add "JUPYTER-APP-LAUNCHER-PATH" to the environment variable, pointing to the manually created "jp_app_launcher. yaml" in the specified directory. 

I manually created the "jupyter_app_launcher" directory in "C:\Users\username\. jupyter" and pointed it to it in the environment variable, allowing jupyterlab to successfully add the launcher
![image](https://github.com/trungleduc/jupyter_app_launcher/assets/61545076/c29e764c-1a5d-4a5a-8038-2a2805b1f006)
![image](https://github.com/trungleduc/jupyter_app_launcher/assets/61545076/272417a7-fda8-490e-b182-d09413d00f5b)
![image](https://github.com/trungleduc/jupyter_app_launcher/assets/61545076/1e098244-7623-49b6-8d12-8552b8d5a31a)

**Comment by trungleduc** [comment]
You need to create the config file by yourself in the default path since the file name is not fixed. 
If you use the environment variable to define the config location, you can set it to anywhere, no need to be in the jupyter path
