### ISSUE TITLE
Don't work in JupyterLab 3.5.2

### ISSUE THREAD

**Issue by santana98** [trungleduc/jupyter_app_launcher#53]
I'm having this error when using version 0.2.1 in JupyterLab 3.5.2

![image](https://github.com/trungleduc/jupyter_app_launcher/assets/38147044/9a973646-e97d-466d-a994-964ee1de225a)

**Comment by trungleduc** [comment]
Please downgrade to `0.1.x` version to use this extension with JupyterLab 3

**Comment by santana98** [comment]
I was able to successfully install version 0.1.7!! Thanks

However, when trying to open a terminal through the launcher I get this error, do you know what configuration might be conflicting?

<img width="1144" alt="image" src="https://github.com/trungleduc/jupyter_app_launcher/assets/38147044/0927949b-c20c-477f-8034-c5aadc50ea11">
