### ISSUE TITLE
Opening a notebook a second time overwrites existing file

### ISSUE THREAD

**Issue by andeplane** [trungleduc/jupyter_app_launcher#58]
It seems like there is [logic in place](https://github.com/trungleduc/jupyter_app_launcher/blob/main/src/factories/notebook/notebook_factory.ts#L32) to handle existing files so you get appended numbers to the file name. However, if I open https://trungleduc.github.io/jupyter_app_launcher/lab/index.html and do
1) Open `Notebook Example`, a new file `Notebook example.ipynb` is created
2) Modify the files with whatever
3) Open launcher again and choose `Notebook Example` again.

Now the changes from step 2 are lost. Would be nice if it rather opened `Notebook example-2.ipynb` instead (like the code seems to attempt to do).

**Comment by trungleduc** [comment]
Thanks for reporting the issue, I will take a lot at it

**Comment by trungleduc** [comment]
Non-reproducible issue


https://github.com/user-attachments/assets/6a26cf67-cc6a-4c44-83bb-113122efc378
