### ISSUE TITLE
Setting an icon overrides the icon for the catalog if catalog is Notebook

### ISSUE THREAD

**Issue by andeplane** [trungleduc/jupyter_app_launcher#59]
I tried using the `icon` property, and used `catalog: Notebook` to have a notebook landing next to the default notebooks. The item appeared, but the `icon` I had used replaced not the item's icon, but the hole catalog (orange frame).

**Comment by trungleduc** [comment]
Could you post your config and a screenshot of the issue?

**Comment by trungleduc** [comment]
closed due to inactivity
