### ISSUE TITLE
Prevent multiple instances at the same time

### ISSUE THREAD

**Issue by pya** [trungleduc/jupyter_app_launcher#60]
Thanks for this great extension.

I am using `local-server` to start an application. This works well. My application should have only one instance. Therefore, I stop my application when the tab, created with a click on the launch button, is closed. This works nicely. But my application breaks if the user opens a second tab, which creates a second instance of my application while the old instance is still running. Is there a way to close a tab when a new one is created?

**Comment by trungleduc** [comment]
hi, for your use case, I would create a custom startup script in python or bash to check for the application instance before starting the web server.

**Comment by trungleduc** [comment]
closed due to inactivity
