### ISSUE TITLE
 Issue: Internal Server Error when Opening Notebook with Voila

### ISSUE THREAD

**Issue by RDWimmers** [trungleduc/jupyter_app_launcher#68]
**Description:**
I'm encountering an issue where attempting to open a notebook with Voila results in an "Internal Server Error." However, the notebook opens and functions correctly when not using Voila.

**Details:**
- The problem occurs specifically when trying to open a notebook with Voila using the `jupyter_app_launcher`.
- There is no copy of the notebook created in the directory.
- Opening the same notebook without Voila works as expected, without any errors.
- The "Render with Voila" button created by the labextension `@voila-dashboards/jupyterlab-preview` works correctly, suggesting that the issue may be related to how Voila is being invoked.

**Question:**
Are there any additional settings or configurations required to open a notebook with Voila as a subprocess? Any guidance on how to resolve this issue would be appreciated.

**Expected Behavior:**
The notebook should open and render correctly when using Voila.

**Actual Behavior:**
An "Internal Server Error" is encountered when opening the notebook with Voila.

![image](https://github.com/user-attachments/assets/6a9dc86d-de87-46ad-bfc4-500a4a02dd36)

**Comment by trungleduc** [comment]
thank for reporting, i will take a look at it

**Comment by RDWimmers** [comment]
I discovered the cause of the "Internal Server Error." The issue stemmed from the file not being found in the JupyterHub environment. The solution was to use the full path `/home/jovyan` instead of the shorthand `~` when specifying the file location.

Thanks for the good work! I am discovering this package, so many possibilities :-)
