### ISSUE TITLE
Consider "soft" dependencies?

### ISSUE THREAD

**Issue by bollwyvl** [trungleduc/jupyter_app_launcher#7]
Great extension!

One observation: the `install_requires` has a lot of heavy hitters... perhaps it's worth considering making these a bit more modular, either with `[extras]` or a `-core` package with subpackages that provide individual features via traitlets/entry_points, with the main package keeping all of them?

**Comment by trungleduc** [comment]
Thanks @bollwyvl for the suggestion, indeed I want to make `voila` related stuffs optional.
