### ISSUE TITLE
Notebook fails to open, with error, or opens in the wrong place

### ISSUE THREAD

**Issue by mwcraig** [trungleduc/jupyter_app_launcher#72]
I think I've found an issue in 0.3.0. The behavior I'm desribing can be seen in this short video [https://youtu.be/MgT8lZo44MY](https://youtu.be/MgT8lZo44MY)  (it seemed like the best way to demonstrate it). The video shows both the jupyter lab window and the console I launched it from.

If I click on a launcher entry for a notebook in a directory other than the one I started jupyter in I often, but not always, get an error like 

```
File Load Error for Notebook 1-3.ipynb
Invalid response: 404 Not Found
```

I've encountered on a jupyterhub server I run but can also reproduce it locally with the repo I mentioned in #66.

On occasion, the notebook appears to open but the kernel it is connected to is one for a notebook in the directory jupyter was started in, not the directory in the sidebar.

That happens more frequently on my hub server than locally.

**Comment by trungleduc** [comment]
Thanks @mwcraig  for reporting, I will take a look
