### ISSUE TITLE
Calling jupyter_app_launcher comand from CLI (via bash)

### ISSUE THREAD

**Issue by MiXaiLL76** [trungleduc/jupyter_app_launcher#79]
Is it possible to call a command, for example "create file" or "open file" via a CURL request to the server?

or opening a new terminal?
There is such an add-on jyg (https://github.com/deathbeds/jyg) that implements similar functionality, but it has not worked with jupyter for a year.

Possible uses:
- Opening a new terminal window
- Launching an application
- Opening a new tab (e.g. with tensorboard)

**Comment by trungleduc** [comment]
> Is it possible to call a command, for example "create file" or "open file" via a CURL request to the server?

This feature is out of the scope of this extension.

**Comment by MiXaiLL76** [comment]
> This feature is out of the scope of this extension.

OK, thank you
